### ISSUE TITLE
Revue signup integration

### ISSUE THREAD

**Issue by NiklasTR** [labdao/landing-page#12]
embed from the revue website:

<div id="revue-embed">
  <form action="http://newsletter.labdao.com/add_subscriber" method="post" id="revue-form" name="revue-form"  target="_blank">
  <div class="revue-form-group">
    <label for="member_email">Email address</label>
    <input class="revue-form-field" placeholder="Your email address..." type="email" name="member[email]" id="member_email">
  </div>
  <div class="revue-form-group">
    <label for="member_first_name">First name <span class="optional">(Optional)</span></label>
    <input class="revue-form-field" placeholder="First name... (Optional)" type="text" name="member[first_name]" id="member_first_name">
  </div>
  <div class="revue-form-group">
    <label for="member_last_name">Last name <span class="optional">(Optional)</span></label>
    <input class="revue-form-field" placeholder="Last name... (Optional)" type="text" name="member[last_name]" id="member_last_name">
  </div>
  <div class="revue-form-actions">
    <input type="submit" value="Subscribe" name="member[subscribe]" id="member_submit">
  </div>
  <div class="revue-form-footer">By subscribing, you agree with Revue’s <a target="_blank" href="https://www.getrevue.co/terms%22%3ETerms of Service</a> and <a target="_blank" href="https://www.getrevue.co/privacy%22%3EPrivacy Policy</a>.</div>
  </form>
</div>

**Comment by NiklasTR** [comment]
`<div id="revue-embed">
  <form action="http://newsletter.labdao.com/add_subscriber" method="post" id="revue-form" name="revue-form"  target="_blank">
  <div class="revue-form-group">
    <label for="member_email">Email address</label>
    <input class="revue-form-field" placeholder="Your email address..." type="email" name="member[email]" id="member_email">
  </div>
  <div class="revue-form-group">
    <label for="member_first_name">First name <span class="optional">(Optional)</span></label>
    <input class="revue-form-field" placeholder="First name... (Optional)" type="text" name="member[first_name]" id="member_first_name">
  </div>
  <div class="revue-form-group">
    <label for="member_last_name">Last name <span class="optional">(Optional)</span></label>
    <input class="revue-form-field" placeholder="Last name... (Optional)" type="text" name="member[last_name]" id="member_last_name">
  </div>
  <div class="revue-form-actions">
    <input type="submit" value="Subscribe" name="member[subscribe]" id="member_submit">
  </div>
  <div class="revue-form-footer">By subscribing, you agree with Revue’s <a target="_blank" href="https://www.getrevue.co/terms%22%3ETerms of Service</a> and <a target="_blank" href="https://www.getrevue.co/privacy%22%3EPrivacy Policy</a>.</div>
  </form>
</div>`

**Comment by NiklasTR** [comment]
I DM'ed you the embedding code and API key

**Comment by janzheng** [comment]
I'm not a fan of adding First and Last name in signup forms as it adds a lot of friction, so I excluded them for now

**Comment by janzheng** [comment]
Jesse was able to fix it by adding an `https://` URL for the newsletter
