### ISSUE TITLE
add link to github and twitter on the top left row

### ISSUE THREAD

**Issue by NiklasTR** [labdao/landing-page#2]
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/18559148/155019039-955ed524-d1b1-41c7-a451-3317b893b0a7.png">

I think it could add value to have a link to twitter and our github in the top right corner of the website. What do you think?

**Comment by janzheng** [comment]
Ok changes pushed to Staging and merged into Main (since it's a small request)

**Comment by NiklasTR** [comment]
perfect! thank you!

**Comment by NiklasTR** [comment]
reopening to suggest we move from "@lab_dao" to "Twitter"
![image](https://user-images.githubusercontent.com/18559148/156934352-439eca63-5c99-44e6-85bb-3435712e1f2f.png)

**Comment by jlevers** [comment]
![image](https://user-images.githubusercontent.com/4974856/156945184-57e139f9-22db-4c91-b7ef-60155193a232.png)

:+1: @NiklasTR
