### ISSUE TITLE
rename "manifesto" to "learn more"

### ISSUE THREAD

**Issue by NiklasTR** [labdao/landing-page#3]
I am working on a gitbook style documentation page that will include these pieces of writing but also more resources - will share the link later

For now, I think it is probably a good idea to just rename the button and attach the link later.

**Comment by NiklasTR** [comment]
adding @jlevers - can you take point on this!

**Comment by jlevers** [comment]
@NiklasTR done :)

**Comment by NiklasTR** [comment]
thank you jesse for changing the assignees!
