### ISSUE TITLE
include link to revue newsletter signup for the website 

### ISSUE THREAD

**Issue by NiklasTR** [labdao/landing-page#5]
@jlevers can you help with frontend things generally?

**Comment by jlevers** [comment]
@NiklasTR can you send me the newsletter signup link? not sure which newsletter you're referring to

**Comment by NiklasTR** [comment]
http://newsletter.labdao.com/ :)

**Comment by janzheng** [comment]
Ok changes pushed to Staging and merged into Main (since it's a small request)

**Comment by janzheng** [comment]
fixed
