### ISSUE TITLE
Dependabot threat evaluation: Cross-site Scripting in Prism

### ISSUE THREAD

**Issue by NiklasTR** [labdao/landing-page#9]
more details: 
https://github.com/labdao/landing-page/security/dependabot/2

do we (how fast?) have to act on this vulnerability?

**Comment by janzheng** [comment]
I bumped the core dependency up and dismissed the alert — other dependencies unfortunately are using an older version, but it shouldn't affect us

**Comment by NiklasTR** [comment]
Thank you @blahah - noted!
